### ISSUE TITLE
Invalid State - The Flow Controller is initializing the Data Flow.

### ISSUE THREAD

**Issue by jrmanes** [Orange-OpenSource/nifikop#121]
## Bug Report

**What did you do?**
I setup the nifi cluster using the operator and deploy it into a namespace, once I try to access to the UI, I got the issue:
**The Flow Controller is initializing the Data Flow**

**What did you expect to see?**
The Nifi UI.

**What did you see instead? Under which circumstances?**
The Flow Controller is initializing the Data Flow

**Environment**
* nifikop version: 0.6.3

go version: 1.15 (dockerfile)

Kubernetes version information: v1.20.7 but also with 1.16, 1.18, 1.20

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-13T02:40:46Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-27T23:27:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

Kubernetes cluster kind:
v1.20.7 but also with 1.16, 1.18, 1.20

NiFi version: 1.12.1

**Possible Solution**
---

That happens when I got to the root path via broswer.

Should I deploy anything else?

The manifest that I deploy is:

```yaml
apiVersion: nifi.orange.com/v1alpha1
kind: NifiCluster
metadata:
  name: nifi
  namespace: nifi-dev
spec:
  service:
    headlessEnabled: true
  zkAddress: "zookeeper.nifi-dev.svc.cluster.local:2181"
  zkPath: "/simplenifi"
  clusterImage: "apache/nifi:1.12.1"
  oneNifiNodePerNode: false
  nodeConfigGroups:
    default_group:
      isNode: true
      storageConfigs:
        - mountPath: "/opt/nifi/nifi-current/logs"
          name: logs
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "retain"
            resources:
              requests:
                storage: 1Gi
      serviceAccountName: "default"
      resourcesRequirements:
        limits:
          cpu: "0.5"
          memory: 2Gi
        requests:
          cpu: "0.5"
          memory: 2Gi
  nodes:
    - id: 0
      nodeConfigGroup: "default_group"
    - id: 1
      nodeConfigGroup: "default_group"
  propagateLabels: true
  nifiClusterTaskSpec:
    retryDurationMinutes: 10
  listenersConfig:
    internalListeners:
      - type: "http"
        name: "http"
        containerPort: 8080
      - type: "cluster"
        name: "cluster"
        containerPort: 6007
      - type: "s2s"
        name: "s2s"
        containerPort: 10000
  externalServices:
    - name: "nifikop-clusterip"
      spec:
        type: ClusterIP
        portConfigs:
          - port: 8080
            internalListenerName: "http"
      serviceAnnotations:
        toto: tata
    - name: "nifikop-srv"
      spec:
        type: NodePort
        portConfigs:
          - port: 8080
            internalListenerName: "http"
      serviceAnnotations:
        toto: tata
```
