### ISSUE TITLE
Controller NifiCluster in endless loop

### ISSUE THREAD

**Issue by arsou33** [Orange-OpenSource/nifikop#146]
## Bug Report

**What did you do?**
Declaring a simple Nifi cluster with two nodes

**What did you expect to see?**
Cluster is starting and NifiKop is stable

**What did you see instead? Under which circumstances?**
Nifi cluster is correctly started but nifiklop NifiCluster controller flood logs
[log.txt](https://github.com/Orange-OpenSource/nifikop/files/7461117/log.txt)

**Environment**
* nifikop version: 7.0.1
* go version: builtin the image

* Kubernetes version information:

* Kubernetes cluster kind:   OVH Managed cluster
* NiFi version: 1.12.1

**Additional context**
Cluster definition

```yml

apiVersion: nifi.orange.com/v1alpha1
kind: NifiCluster
metadata:
  name: nifi
spec:
  service:
    headlessEnabled: true
  zkAddress: "zookeeper:2181"
  zkPath: "/nifi"
  clusterImage: "apache/nifi:1.12.1"
  oneNifiNodePerNode: false
  nodeConfigGroups:
    default_group:
      isNode: true
      storageConfigs:
        - mountPath: "/opt/nifi/nifi-current/logs"
          name: logs
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "csi-cinder-high-speed"
            resources:
              requests:
                storage: 10Gi
      serviceAccountName: "default"
      resourcesRequirements:
        limits:
          cpu: "0.5"
          memory: 2Gi
        requests:
          cpu: "0.5"
          memory: 2Gi
  nodes:
    - id: 1
      nodeConfigGroup: "default_group"
    - id: 2
      nodeConfigGroup: "default_group"
  propagateLabels: true
  nifiClusterTaskSpec:
    retryDurationMinutes: 10
  listenersConfig:
    internalListeners:
      - type: "http"
        name: "http"
        containerPort: 8080
      - type: "cluster"
        name: "cluster"
        containerPort: 6007
      - type: "s2s"
        name: "s2s"
        containerPort: 10000
      - type: "prometheus"
        name: "prometheus"
        containerPort: 9090
  externalServices:
    - name: "clusterip"
      spec:
        type: ClusterIP
        portConfigs:
          - port: 8080
            internalListenerName: "http"

```
