### ISSUE TITLE
Add ability to attach additional labels to NiFi pods

### ISSUE THREAD

**Issue by michael81877** [Orange-OpenSource/nifikop#149]
## Feature Request

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like to see**
I'd like to attach arbitrary labels to pods that nifikop creates. Specifically, i'd like to label pods with meaningful things as a means to select pods for log aggregation via https://rancher.com/docs/rancher/v2.6/en/logging/

For example:

```
apiVersion: nifi.orange.com/v1alpha1
kind: NifiCluster
metadata:
  name: simplenifi
spec:
  ...
  pod:
    labels:
      specific-pod-label: "abc"
  nodeConfigGroup:
    default_group:
      nodeLabels:
        my-special-label: "true"
  ...
```

**Describe alternatives you've considered**
Annotations can't be used as pod selectors and the only labels applied to the pods nifikop creates match the name of the `NiFiCluster` CRD under the label `nifi_cr`. Otherwise, there's not a label that distinguishes multiple nifi clusters deployed by nifikop.
