### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by npapapietro** [Orange-OpenSource/nifikop#155]
## Bug Report

**What did you do?**
The fields

```yaml
apiVersion: nifi.orange.com/v1alpha1
kind: NifiCluster
...
spec:
  ...
  clusterSecure: true
  siteToSiteSecure: true
```
are no longer present on the CRD, but still used through out examples and documentation.

**What did you expect to see?**
A mention somewhere about where they went and updating in `helm/nifikop/README.md` about the version they were removed in.

**Environment**
* nifikop version: 0.7.2

**Possible Solution**
I removed them from my NifiCluster but not sure what that means.
