### ISSUE TITLE
OIDC: The login request identifier was not found in the request

### ISSUE THREAD

**Issue by HaythemHorbit** [Orange-OpenSource/nifikop#76]
## Type of question
Need a  help around nifikop and OIDC
## Question

**What did you do?**
Hello, I have a problem with Nifi & OIDC
Im getting this message: The login request identifier was not found in the request. Unable to continue.

```
2021-02-11 15:25:45,778 INFO [NiFi Web Server-19] o.a.n.w.a.c.IllegalArgumentExceptionMapper java.lang.IllegalArgumentException: The login request identifier was not found in the request. Unable to continue.}. Returning Bad Request} response.
java.lang.IllegalArgumentException: The login request identifier was not found in the request. Unable to continue.
	at org.apache.nifi.web.api.AccessResource.oidcExchange(AccessResource.java:306)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
...
2021-02-11 15:26:09,483 WARN [NiFi Web Server-18] o.a.n.w.a.c.IllegalStateExceptionMapper java.lang.IllegalStateException: Cannot create group 'nifi-sslnifi.managed-nodes' with users that don't exist.. Returning Conflict response.
java.lang.IllegalStateException: Cannot create group 'nifi-sslnifi.managed-nodes' with users that don't exist.
	at org.apache.nifi.authorization.AuthorizerFactory$1$1$1.addGroup(AuthorizerFactory.java:275)
	at org.apache.nifi.web.dao.impl.StandardPolicyBasedAuthorizerDAO.createUserGroup(StandardPolicyBasedAuthorizerDAO.java:253)
	at org.apache.nifi.web.dao.impl.StandardPolicyBasedAuthorizerDAO$$FastClassBySpringCGLIB$$ea190383.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
```

**What did you expect to see?**
Access to Nifi UI with my credentials 
**What did you see instead? Under which circumstances?**
The login request identifier was not found in the request. Unable to continue.

**Environment**
* nifikop version: 
v0.5.2-release 
* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:  
docker-desktop

* NiFi version:
apache/nifi:1.12.1

**Additional context**

```yaml
apiVersion: nifi.orange.com/v1alpha1
kind: NifiCluster
metadata:
  name: sslnifi
spec:
  service:
    headlessEnabled: true
  zkAddress: "nifi-cluster-zookeeper:2181"
  zkPath: "/ssllnifi"
  clusterImage: "apache/nifi:1.12.1"
  oneNifiNodePerNode: false
  managedAdminUsers:
    -  identity : "<myname1>@gmail.com"
       name: "<myname1>"
  managedReaderUsers:
     - identity : "<myname>@gmail.com"
       name: "<myname>"
  propagateLabels: true
  nifiClusterTaskSpec:
    retryDurationMinutes: 10
  readOnlyConfig:
    # NifiProperties configuration that will be applied to the node.
    nifiProperties:
      webProxyHosts:
        - nifi.hhorbit.com
      # Additionnals nifi.properties configuration that will override the one produced based
      # on template and configurations.
      overrideConfigs: |
        nifi.security.user.oidc.discovery.url=https://accounts.google.com/.well-known/openid-configuration
        nifi.security.user.oidc.client.id=172548331581-cv249kc5s981mdvv4oajrkg21a6pv2en.apps.googleusercontent.com
        nifi.security.user.oidc.client.secret=l06y6ZL2m2Ivwe1JjDkHwTw-
        nifi.security.identity.mapping.pattern.dn=CN=([^,]*)(?:, (?:O|OU)=.*)?
        nifi.security.identity.mapping.value.dn=$1
        nifi.security.identity.mapping.transform.dn=NONE
  nodeConfigGroups:
    default_group:
      isNode: true
      storageConfigs:
        - mountPath: "/opt/nifi/nifi-current/logs"
          name: logs
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "standard"
            resources:
              requests:
                storage: 10Gi
        - mountPath: "/opt/nifi/data"
          name: data
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "standard"
            resources:
              requests:
                storage: 10Gi
        - mountPath: "/opt/nifi/flowfile_repository"
          name: flowfile-repository
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "standard"
            resources:
              requests:
                storage: 10Gi
        - mountPath: "/opt/nifi/nifi-current/conf"
          name: conf
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "standard"
            resources:
              requests:
                storage: 10Gi
        - mountPath: "/opt/nifi/content_repository"
          name: content-repository
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "standard"
            resources:
              requests:
                storage: 10Gi
        - mountPath: "/opt/nifi/provenance_repository"
          name: provenance-repository
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: "standard"
            resources:
              requests:
                storage: 10Gi
      serviceAccountName: "default"
  nodes:
    - id: 0
      nodeConfigGroup: "default_group"
    - id: 2
      nodeConfigGroup: "default_group"
  listenersConfig:
    internalListeners:
      - type: "https"
        name: "https"
        containerPort: 8443
      - type: "cluster"
        name: "cluster"
        containerPort: 6007
      - type: "s2s"
        name: "s2s"
        containerPort: 10000
    sslSecrets:
     tlsSecretName: "test-nifikop"
     create: true
```

ingress 

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  name: nifi-ingress
  namespace: nifi
spec:
  rules:
  - host: nifi.hhorbit.com
    http:
      paths:
      - backend:
          service:
            name: sslnifi-headless
            port:
              number: 8443
        path: /
        pathType: Prefix
```

nifi@sslnifi-0-node:/opt/nifi/nifi-current$ cat ../data/users.xml 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tenants>
    <groups>
        <group identifier="91e20849-0177-1000-0000-00002729af34" name="nifi-sslnifi.managed-readers">
            <user identifier="91e20103-0177-1000-ffff-ffffb917ab0a"/>
        </group>
    </groups>
    <users>
        <user identifier="38ca2751-725d-39c1-a298-be545cb1a416" identity="sslnifi-0-node.sslnifi-headless.nifi.svc.cluster.local"/>
        <user identifier="6b78b042-ccd2-398d-87a9-65476b87d032" identity="sslnifi-controller.nifi.mgt.cluster.local"/>
        <user identifier="ac4b3e9b-4220-36ec-b87a-8791580d3203" identity="sslnifi-2-node.sslnifi-headless.nifi.svc.cluster.local"/>
        <user identifier="91e1f922-0177-1000-ffff-fffff503fda3" identity="<myname>@gmail.com"/>
        <user identifier="91e20103-0177-1000-ffff-ffffb917ab0a" identity="<myname1>@gmail.com"/>
    </users>
</tenants>
```

nifi@sslnifi-0-node:/opt/nifi/nifi-current$ cat ../data/authorizations.xml 
```xml

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<authorizations>
    <policies>
        <policy identifier="f99bccd1-a30e-3e4a-98a2-dbc708edc67f" resource="/flow" action="R">
            <user identifier="6b78b042-ccd2-398d-87a9-65476b87d032"/>
        </policy>
        <policy identifier="b8775bd4-704a-34c6-987b-84f2daf7a515" resource="/restricted-components" action="W">
            <user identifier="6b78b042-ccd2-398d-87a9-65476b87d032"/>
        </policy>
        <policy identifier="627410be-1717-35b4-a06f-e9362b89e0b7" resource="/tenants" action="R">
            <user identifier="6b78b042-ccd2-398d-87a9-65476b87d032"/>
        </policy>
        <policy identifier="15e4e0bd-cb28-34fd-8587-f8d15162cba5" resource="/tenants" action="W">
            <user identifier="6b78b042-ccd2-398d-87a9-65476b87d032"/>
        </policy>
        <policy identifier="ff96062a-fa99-36dc-9942-0f6442ae7212" resource="/policies" action="R">
            <user identifier="6b78b042-ccd2-398d-87a9-65476b87d032"/>
        </policy>
        <policy identifier="ad99ea98-3af6-3561-ae27-5bf09e1d969d" resource="/policies" action="W">
            <user identifier="6b78b042-ccd2-398d-87a9-65476b87d032"/>
        </policy>
        <policy identifier="2e1015cb-0fed-3005-8e0d-722311f21a03" resource="/controller" action="R">
            <user identifier="6b78b042-ccd2-398d-87a9-65476b87d032"/>
        </policy>
        <policy identifier="c6322e6c-4cc1-3bcc-91b3-2ed2111674cf" resource="/controller" action="W">
            <user identifier="6b78b042-ccd2-398d-87a9-65476b87d032"/>
        </policy>
        <policy identifier="287edf48-da72-359b-8f61-da5d4c45a270" resource="/proxy" action="W">
            <user identifier="38ca2751-725d-39c1-a298-be545cb1a416"/>
            <user identifier="ac4b3e9b-4220-36ec-b87a-8791580d3203"/>
        </policy>
    </policies>
</authorizations>
````

```xml
