### ISSUE TITLE
Node Affinity attributes missing for Pods

### ISSUE THREAD

**Issue by apothini** [Orange-OpenSource/nifikop#78]
Node Affinity attributes missing for Pods - Please let us know how can node affinity set through values.yaml

**Comment by vodwood** [comment]
This seems to work with 0.6.0-release:
```
spec:
  service:
    headlessEnabled: true
  zkAddress: "zookeeper.nifi-lab.svc.cluster.local:2181"
  zkPath: "/simplenifi"
  clusterImage: "apache/nifi:1.12.1"
  oneNifiNodePerNode: false
  nodeConfigGroups:
    default_group:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: app-intent
              operator: In
              values:
              - nifi
```
