### ISSUE TITLE
[BUG] Parameter Context with no value set when the value field is missing or empty

### ISSUE THREAD

**Issue by juldrixx** [Orange-OpenSource/nifikop#79]
## Bug Report

**What did you do?**
I deployed a NiFi Dataflow with a NiFi Parameter Context. In the NiFi Parameter Context, one of the parameter did not have a `value` field or the `value` field was empty.

**What did you expect to see?**
In the NiFi, i should have seen a parameter with an empty string as value.

**What did you see instead? Under which circumstances?**
In the NiFi, i have seen a parameter with no value set.

**Environment**
* nifikop version: 

v0.5.2 

* Kubernetes version information:

v1.16.15-gke.7800

* Kubernetes cluster kind: 

GKE

* NiFi version:

1.12.1

**Possible Solution**
Set value to empty string as default value in every circumstance. 

**Example**
```yaml
apiVersion: nifi.orange.com/v1alpha1
kind: NifiParameterContext
metadata:
  creationTimestamp: "2021-02-27T17:45:05Z"
  finalizers:
  - finalizer.nifiparametercontexts.nifi.orange.com
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
    heritage: Helm
    nifiCluster: ojse54e49.instances
    release: squid-mapping-enrichment-c641f193d0ab6716e7e3
    uuid: 54e4901008be4dfebe88ef420efe75a7
  name: oem-jg-sqdf-enri-pc
  namespace: instances
  uid: ccf960b4-a59a-4315-b4d0-a65370974d79
spec:
  clusterRef:
    name: ojse54e49
    namespace: instances
  description: 'Parameter context for the cluster: ojse54e49'
  parameters:
  - description: SquidFlow instance name
    name: squidflow_instance_name
    value: squidflow
  - description: Record Path of the timestamp field dating the event
    name: ts_field
status:
  id: e49d25a6-0177-1000-0000-000027658bd4
  version: 2
```
