### ISSUE TITLE
Admin user not working with managedAdminUsers tag

### ISSUE THREAD

**Issue by celsomarques** [Orange-OpenSource/nifikop#95]
## Question

How can I fix this? Thanks.

**What did you do?**
I'm running Nifi inside GKE and using managedAdminUsers tag.

```
apiVersion: nifi.orange.com/v1alpha1
kind: NifiCluster
metadata:
  name: nifi
  namespace: nifi
spec:
  service:
    headlessEnabled: true
  zkAddress: "zookeeper.default.svc.cluster.local:2181"
  zkPath: "/sec"
  clusterImage: "apache/nifi:1.12.1"
  oneNifiNodePerNode: false
  managedAdminUsers:
  - identity : "xxxx@gmail.com"
    name: "user"
  propagateLabels: true
  ...
```

**What did you expect to see?**
I expected to see the admin user under nifi/data/user.xml and nifi/data/authorizations.xml.

**What did you see instead? Under which circumstances?**
There is no user created using the above tag.

**Environment**
* nifikop version:

 0.6.0-release

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-gke.502", GitCommit:"a2a88ab32201dca596d0cdb116bbba3f765ebd36", GitTreeState:"clean", BuildDate:"2021-03-08T22:06:24Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

GKE -> 1.18.16-gke.502 

* NiFi version:

1.12.1
